-- Active: 1680928443591@@127.0.0.1@3306@silva
CREATE DATABASE IF NOT EXISTS SILVA;
-- USE SILVA
CREATE TABLE IF NOT EXISTS datos(
    id INT,
    nombre VARCHAR(45),
    apellidop VARCHAR(45),
    apellidom VARCHAR(45)
);

ALTER TABLE datos ADD PRIMARY KEY (id);

ALTER TABLE datos MODIFY id INT AUTO_INCREMENT, AUTO_INCREMENT=1;